### ISSUE TITLE
LaTeX Formatting of Expressions and Equations

### ISSUE THREAD

**Issue by balacij** [Akshobhya1234/MSc-thesis#2]
Take this as an example:

https://github.com/Akshobhya1234/MSc-thesis/blob/11f64f4c75d8060e83229211c42648c5d7d20626/UniversalAlgebra.tex#L8

When writing mathematics in LaTeX, you should use `\(x \in R\)` if you want _inlined_ mathematical equations (i.e., held within the paragraph, not special). Alternatively, if you want to highlight and center your mathematical equations as blocks (as opposed to in the paragraphs) , you can use `\[x \in R\]`.

Also, you should include the mathematical variables and whatnot inside the `\(` and `\)` (or `\[` and `\]` as appropriately), not just the operations.

From the example, you should write `\(x \times x\)` instead of `x \(\times\) x`, and `R = \{ (x,x) | x \in X \}`.

**Comment by Akshobhya1234** [comment]
Ah, good catch. It was my trick to play with spacing. This issue will likely exist in other chapters. I will work on it. Thanks!

**Comment by balacij** [comment]
If you need extra spacing between characters, you can use `\ ` to force a space, and `~` to force a space but disallowing linebreaks at that point (e.g., `Dr.\ Jacques Carette` is allowed to break between `Dr.` and `Jacques`, but `Dr.~Jacques Carette` would not allow the line break between `Dr.` and `Jacques`.

**Comment by balacij** [comment]
Also, if you use VS Code's LaTeX plugin, it has a list of TeX macros you can use (click the TeX plugin on the LHS, then open the symbol panel). In particular, for mathematical symbols, it's very helpful :smile:

**Comment by Akshobhya1234** [comment]
Yes, I was installing the plugins. It seems to be helpful. Especially language support. Thanks Jason!

**Comment by Akshobhya1234** [comment]
Done. Thanks!
